# Generated by Django 4.2.7 on 2023-12-06 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('guid', models.CharField(blank=True, max_length=36)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('guid', models.CharField(blank=True, max_length=36)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(blank=True, default=None, null=True)),
                ('long_name', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=256)),
                ('f_address', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('guid', models.CharField(blank=True, max_length=36)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(blank=True, default=None, null=True)),
                ('id_parent', models.IntegerField(blank=True)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField(blank=True)),
                ('department_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structure.departmenttype')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structure.factory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
