# Generated by Django 4.2.7 on 2023-12-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='id_department_type',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='id_parent_guid',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='guid',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='id_parent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='departmenttype',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='departmenttype',
            name='guid',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='f_address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='guid',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
