# Generated by Django 4.2.7 on 2023-12-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_alter_department_edited_alter_departmenttype_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='guid',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='departmenttype',
            name='guid',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='guid',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
