# Generated by Django 4.2.7 on 2023-12-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_alter_department_guid_alter_departmenttype_guid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='id_parent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='f_address',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
