# Generated by Django 4.2.7 on 2023-12-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_department_id_department_type_and_more'),
        ('structure', '0004_alter_department_date_end_alter_department_id_parent_and_more'),
    ]

    operations = [
    ]
